apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.owner }}/${{ values.repo }}
    argocd/app-name: ${{ values.name }}
    argocd/app-namespace: argocd
    argocd/instance-name: main
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: demo-apps
    backstage.io/kubernetes-label-selector: app=${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    quay.io/repository-slug: ${{ values.quayNamespace }}/${{ values.name }}
  links:
    - url: https://github.com/${{ values.owner }}/${{ values.repo }}
      title: GitHub Repository
      icon: github
    - url: https://github.com/${{ values.owner }}/${{ values.repo }}/actions
      title: GitHub Actions
      icon: dashboard
    - url: https://quay.io/repository/${{ values.quayNamespace }}/${{ values.name }}
      title: Container Image
      icon: docker
    - url: http://localhost:8080/applications/argocd/${{ values.name }}
      title: ArgoCD App
      icon: cloud
  tags:
    - landing
    - kubernetes
    - event
    - gitops
spec:
  type: website
  lifecycle: production
  owner: guests
  system: landing-system
