apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: events-api
  description: API to manage Cloud Native events
  tags:
    - rest
    - openapi
    - events
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: landing-system
  definition: |
    openapi: 3.0.0
    info:
      title: Events API
      description: API to manage Cloud Native events
      version: 1.0.0
    servers:
      - url: https://api.example.com/v1
        description: Production server
      - url: http://localhost:3001/v1
        description: Local development
    paths:
      /events:
        get:
          summary: List all events
          description: Returns a list of all available events
          operationId: listEvents
          tags:
            - events
          parameters:
            - name: status
              in: query
              description: Filter by event status
              schema:
                type: string
                enum: [upcoming, active, completed]
            - name: limit
              in: query
              description: Maximum number of results
              schema:
                type: integer
                default: 10
                maximum: 100
          responses:
            '200':
              description: List of events
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
            '500':
              description: Internal server error
        post:
          summary: Create a new event
          description: Creates a new event in the system
          operationId: createEvent
          tags:
            - events
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CreateEventRequest'
          responses:
            '201':
              description: Event created successfully
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Event'
            '400':
              description: Invalid data
            '401':
              description: Unauthorized
      /events/{eventId}:
        get:
          summary: Get event by ID
          operationId: getEvent
          tags:
            - events
          parameters:
            - name: eventId
              in: path
              required: true
              description: Unique event ID
              schema:
                type: string
                format: uuid
          responses:
            '200':
              description: Event details
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Event'
            '404':
              description: Event not found
        put:
          summary: Update an event
          operationId: updateEvent
          tags:
            - events
          parameters:
            - name: eventId
              in: path
              required: true
              schema:
                type: string
                format: uuid
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/UpdateEventRequest'
          responses:
            '200':
              description: Event updated
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Event'
            '404':
              description: Event not found
        delete:
          summary: Delete an event
          operationId: deleteEvent
          tags:
            - events
          parameters:
            - name: eventId
              in: path
              required: true
              schema:
                type: string
                format: uuid
          responses:
            '204':
              description: Event deleted
            '404':
              description: Event not found
      /events/{eventId}/speakers:
        get:
          summary: List event speakers
          operationId: listEventSpeakers
          tags:
            - speakers
          parameters:
            - name: eventId
              in: path
              required: true
              schema:
                type: string
                format: uuid
          responses:
            '200':
              description: List of speakers
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Speaker'
      /health:
        get:
          summary: Health check
          operationId: healthCheck
          tags:
            - system
          responses:
            '200':
              description: Service healthy
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        example: healthy
                      timestamp:
                        type: string
                        format: date-time
    components:
      schemas:
        Event:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
              example: Cloud Native Summit 2025
            description:
              type: string
            date:
              type: string
              format: date-time
            location:
              type: string
              example: Virtual
            status:
              type: string
              enum: [upcoming, active, completed]
            capacity:
              type: integer
            registeredAttendees:
              type: integer
            tags:
              type: array
              items:
                type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
        CreateEventRequest:
          type: object
          required:
            - name
            - date
            - location
          properties:
            name:
              type: string
              minLength: 3
              maxLength: 100
            description:
              type: string
              maxLength: 500
            date:
              type: string
              format: date-time
            location:
              type: string
            capacity:
              type: integer
              minimum: 1
            tags:
              type: array
              items:
                type: string
        UpdateEventRequest:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            date:
              type: string
              format: date-time
            location:
              type: string
            status:
              type: string
              enum: [upcoming, active, completed]
            capacity:
              type: integer
        Speaker:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
              example: Jane Doe
            bio:
              type: string
            company:
              type: string
            role:
              type: string
            photoUrl:
              type: string
              format: uri
            socialLinks:
              type: object
              properties:
                twitter:
                  type: string
                linkedin:
                  type: string
                github:
                  type: string
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - bearerAuth: []
