apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl.owner }}/${{ values.repoUrl.repo }}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{ values.name }}
  tags:
    - nodejs
    - kubernetes
spec:
  type: service
  lifecycle: experimental
  owner: guests
